[WIP] unified naming convention
alibaba/hessian2-codec pull request #6
Opened 2021-01-18 12:30 UTC by wbpcode

Signed-off-by: wbpcode <comems@msn.com>

* Unified naming convention.
* Keep naming convension same with (envoy)[https://github.com/envoyproxy/envoy/blob/main/STYLE.md].

2021-01-18 12:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hessian2-codec?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hessian2-codec?pullRequest=6) before we can accept your contribution.<br/><hr/>**wbpcode** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hessian2-codec?pullRequest=6) it.</sub>

2021-01-20 15:33 UTC, zyfjeff requested changes
Great work, Some small comments.

2021-01-20 15:33 UTC, zyfjeff commented on common/common.h
>  class utils {
utils -> Utils?

2021-01-20 15:33 UTC, zyfjeff commented on example/custom_type.cc
> +void from_hessian(Person&, ::Hessian2::Decoder&);
from_hessian -> fromHessian?

2021-01-20 15:33 UTC, zyfjeff commented on example/custom_type.cc
> +bool to_hessian(const Person&, ::Hessian2::Encoder&);
ditto

2021-01-21 01:43 UTC, wbpcode commented on common/common.h
>  class utils {
Get it.

2021-01-21 02:51 UTC, zyfjeff commented
Great work! 🎉

2021-01-21 02:51 UTC, zyfjeff approved these changes

2021-01-21 02:51 UTC, merged